
import { NextResponse, NextRequest } from "next/server";
import { auth } from "@/lib/auth/auth";
import { prisma } from "@/lib/db/prisma";
import { SlideNode } from "@/types/slide";

// ─── Helper: node → HTML string ───────────────────────────────────────────────

function nodeToHTML(node: SlideNode, depth = 0): string {
  const indent = "  ".repeat(depth);
  const attrs = Object.entries(node.attributes ?? {})
    .map(([k, v]) => `${k}="${v}"`)
    .join(" ");
  const classAttr = node.className ? ` class="${node.className}"` : "";
  const attrsStr = attrs ? ` ${attrs}` : "";

  if (node.tag === "img") {
    return `${indent}<img src="${node.content ?? ""}"${classAttr}${attrsStr} />\n`;
  }

  const voidTags = ["img", "br", "hr", "input"];
  if (voidTags.includes(node.tag)) {
    return `${indent}<${node.tag}${classAttr}${attrsStr} />\n`;
  }

  const children = node.children?.map((c) => nodeToHTML(c, depth + 1)).join("") ?? "";
  const content = node.content ? node.content : children;

  return `${indent}<${node.tag}${classAttr}${attrsStr}>\n${
    children || (node.content ? `${indent}  ${node.content}\n` : "")
  }${indent}</${node.tag}>\n`;
}

// ─── Helper: node → React JSX string ─────────────────────────────────────────

function nodeToJSX(node: SlideNode, depth = 0): string {
  const indent = "  ".repeat(depth);
  const attrs = Object.entries(node.attributes ?? {})
    .map(([k, v]) => (k === "class" ? `className="${v}"` : `${k}="${v}"`))
    .join(" ");
  const classAttr = node.className ? ` className="${node.className}"` : "";
  const attrsStr = attrs ? ` ${attrs}` : "";

  if (node.tag === "img") {
    return `${indent}<img src="${node.content ?? ""}"${classAttr}${attrsStr} alt="${node.attributes?.alt ?? ""}" />\n`;
  }

  const children = node.children?.map((c) => nodeToJSX(c, depth + 1)).join("") ?? "";
  const content = node.content ? node.content : children;

  return `${indent}<${node.tag}${classAttr}${attrsStr}>\n${
    children || (node.content ? `${indent}  ${node.content}\n` : "")
  }${indent}</${node.tag}>\n`;
}

// ─── POST /api/projects/[id]/slides/[slideId]/export ─────────────────────────

export async function POST(
  req: NextRequest,
  { params }: { params: { id: string; slideId: string } }
) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id, slideId } = params;
  const { format, slideSettings } = await req.json();

  const project = await prisma.project.findUnique({ where: { id } });
  if (!project || project.userId !== session.user.id)
    return NextResponse.json({ error: "Not found" }, { status: 404 });

  const slide = await prisma.slide.findUnique({ where: { id: slideId } });
  if (!slide) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const nodes: SlideNode[] = slide.nodes as unknown as SlideNode[];

  // ── Background style ──────────────────────────────────────────────────────
  const bgStyle =
    slideSettings?.backgroundType === "gradient"
      ? `background: linear-gradient(${slideSettings.gradientAngle ?? 135}deg, ${slideSettings.gradientFrom ?? "#0f172a"}, ${slideSettings.gradientTo ?? "#1e293b"});`
      : `background-color: ${slideSettings?.backgroundColor ?? "#0f172a"};`;

  const nodesHTML = nodes.map((n) => nodeToHTML(n, 4)).join("");
  const nodesJSX = nodes.map((n) => nodeToJSX(n, 6)).join("");

  // ── HTML export ───────────────────────────────────────────────────────────
  if (format === "html") {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${slide.title ?? "Slide"}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body>
  <section
    style="width:${slideSettings?.canvasWidth ?? 800}px; min-height:${slideSettings?.canvasHeight ?? 450}px; padding:${slideSettings?.padding ?? 32}px; display:flex; flex-direction:column; gap:${slideSettings?.gap ?? 16}px; ${bgStyle}"
  >
${nodesHTML}  </section>
</body>
</html>`;
    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="slide-${slideId}.html"`,
      },
    });
  }

  // ── React Component export ─────────────────────────────────────────────────
  if (format === "react") {
    const componentName = `Slide_${slideId.replace(/-/g, "_")}`;
    const jsx = `// Generated by Slide Builder
import React from "react";

export function ${componentName}() {
  return (
    <section
      style={{
        width: ${slideSettings?.canvasWidth ?? 800},
        minHeight: ${slideSettings?.canvasHeight ?? 450},
        padding: ${slideSettings?.padding ?? 32},
        display: "flex",
        flexDirection: "column",
        gap: ${slideSettings?.gap ?? 16},
        ${
          slideSettings?.backgroundType === "gradient"
            ? `background: "linear-gradient(${slideSettings.gradientAngle ?? 135}deg, ${slideSettings.gradientFrom}, ${slideSettings.gradientTo})"`
            : `backgroundColor: "${slideSettings?.backgroundColor ?? "#0f172a"}"`
        },
      }}
    >
${nodesJSX}    </section>
  );
}
`;
    return new NextResponse(jsx, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="Slide_${slideId}.tsx"`,
      },
    });
  }

  return NextResponse.json({ error: "Invalid format. Use: html | react" }, { status: 400 });
}
